### ISSUE TITLE
Windows version crashes on 'Improve' while having 3 stars

### ISSUE THREAD

**Issue by skruseman** [felicien-brochu/selflessheroes#4] opened 2020-04-04 18:06 UTC
**Describe the bug**
Having 3 stars for level #4 'Separate ways', the window goes all white when pressing 'Improve'.

**To Reproduce**
Context: I have at least 1 star for the first 7 levels. 
1. I then wanted to improve on level 'Separate ways'.
2. I succeeded on secondary goal 'max. 6 lines' (thanks to the hint). 
3. Wait for 3x fireworks.
4. Then I pressed 'Improve'
5. The window goes all white; have to force close the window and restart.
6. Re-entered the game 
7. Went straight back to level 4 and re-did the actions
8. Same white screen
9. Restart again
10. Now try the same for levels 1 and 2
11. Behavior is as expected.
12. Now try level 4 again.
13. No white screen, behavior as expected.

**Expected behavior**
I expected to be returned to the level 4, able to try out something different.

**Screenshots**
N/A

**Platform**
 - OS: Windows 10, 64bit
 - Application type: Windows installer
 - Version: v1.1.0 , English

**Additional context**
N/A

**Comment by felicien-brochu** [comment] 2020-04-04 18:50
I am unable to reproduce the bug. I am pretty sure it is not related to this specific level because someone told me he encountered the same bug in other levels. It could be caused by a bug in dependencies.
If it's recurrent, let me know and I'll take the time to investigate further. But for now I cannot begin to guess where it's coming from.

**Comment by skruseman** [comment] 2020-04-04 23:32
I understand. Also, it's not a common use case, wishing to improve while you just earned all 3 stars.

**Comment by felicien-brochu** [comment] 2020-04-17 08:45
This issue should be resolved in v1.2.0. due to electron update.

**Closed by felicien-brochu** 2020-04-17 08:45 UTC
Labels: bug, good first issue, on hold
